FROM supabase/storage-api:v1.11.13

# ANON_KEY, SERVICE_KEY, PGRST_JWT_SECRET et DATABASE_URL viennent de docker-compose
ENV POSTGREST_URL=http://rest:3000
ENV FILE_SIZE_LIMIT=524288000
ENV STORAGE_BACKEND=file
ENV FILE_STORAGE_BACKEND_PATH=/var/lib/storage
ENV TENANT_ID=stub
ENV REGION=stub
ENV GLOBAL_S3_BUCKET=stub
ENV ENABLE_IMAGE_TRANSFORMATION=true
ENV IMGPROXY_URL=http://imgproxy:8080
ENV SERVER_PORT=5002

COPY proxy.js /proxy.js

ENTRYPOINT ["/bin/sh", "-c", "node /proxy.js & node /app/dist/index.js"]
